name: Unit Test Case

on:
  pull_request:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test-case:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out...
        uses: actions/checkout@v2
      - name: Install modules in root
        run: yarn install
      - name: Install modules in schema
        working-directory: ./schema
        run: yarn install
      - name: Run UnitTestCase
        working-directory: ./schema
        run: npm test
